### ISSUE TITLE
Blacklist module settings. hide users combobox shuffle data after save-load

### ISSUE THREAD

**Issue by Usernm0** [DeForce/multichat_python#463]
Build: Develop-2

Steps to reproduce:
1. Open settings -> Messaging Modules -> Blacklist
2. Add 3 users to hide with names: 1, 2, 3
3. Save settings via OK button.
4. Open settings -> Messaging Modules -> Blacklist

Expected:
3 entry in table with order: 1, 2, 3
Bug:
3 entry in table with order: 1, 3, 2

Blacklist.cfg:
```
users_hide:
- '1'
- '3'
- '2'
```

**Comment by DeForce** [comment]
Controls will now retain the order
