### ISSUE TITLE
Blacklist module settings. Hide users combobox not save more than 7 entries.

### ISSUE THREAD

**Issue by Usernm0** [DeForce/multichat_python#464]
Build: Develop-2

Steps to reproduce:
1. Open settings -> Messaging Modules -> Blacklist
2. Add 7 users to hide with names: 1, 2, 3, 4, 5, 6, 7 
3. Save settings via OK button.
4. Open settings -> Messaging Modules -> Blacklist
5. Add 1 more user. Name 8 for example.
6. Save settings via OK button.
7. Open settings -> Messaging Modules -> Blacklist

Expected:
Table with 8 entities.

Bug:
Table with entities on step 2.

Error in console on step 5:
```
Traceback (most recent call last):
  File "src\modules\gui.py", line 641, in button_clicked
  File "src\modules\gui.py", line 391, in on_list_operation
KeyError: 'blacklist.users_hide'
```
Entity appear after step 5 in table.

Entity not saved in config on step 6.

New entity not appear on step 7.

**Comment by DeForce** [comment]
Fixed
