### ISSUE TITLE
Settings menu not restore minimized window

### ISSUE THREAD

**Issue by Usernm0** [DeForce/multichat_python#465]
Build: Develop-2

Steps to reproduce:
1. Open Settings.
2. Minimize Settings window.
3. Click on Settings menu.

Expected:
Settings window restored.

Bug:
Nothing happens.

**Comment by Usernm0** [comment]
Build: Develop-7

Still not open settings back. Just change active window focus to minimized window.

**Comment by DeForce** [comment]
Should be fixed now
